### ISSUE TITLE
[?][8.0][mail_tracking] How to track user clicks

### ISSUE THREAD

**Issue by ivantodorovich** [OCA/social#122]
@pedrobaeza @antespi, I ping you two because you are the contributors of this module.

I'm trying to figure out how to track user clicks on email links.
I thought it was possible, because the `event_type:` `click` exists and its tested.

However, after looking at the controller's code, it seems there's no route to handle this event (IMO: it should track the event and then redirect to the desired url through headers)

Am I missing something big on how to use this, or is this functionality indeed not yet implemented?

**Comment by antespi** [comment]
This functionality is not implemented. mail_tracking is also a base addon for other ones that integrate event webhooks, for instance, mail_tracking_mailgun.

This could be a good improve to mail_tracking. In order to have a todo list, we have to:
- Create a new table in order to save the relation of link to an unique token. 
- Replace all links in email body with the link to a new controller (this new link will include only the database name, the unique token and the tracking_email_id). 
- Controller will look up the table (using the unique token) and return a redirect to the real link. 
- Also controller will create a click tracking_email_event with all the available metadata associated with the HTTP request (IP, user_agent, timestamp, etc ...)

With this improvement, an Odoo instance that use a simple SMTP service (in localhost, for instance) will have sent, open and click events out-of-the-box.

**Comment by ivantodorovich** [comment]
Yeah, that will be really good.

I already solved my pressing issue using Google Analytics, but I'll make a PR with this improvements as soon as I have the time. Having all the tracking data in Odoo would be really awesome.

**Comment by pedrobaeza** [comment]
Don't close this then until it's done. I assign you in the issue.

**Comment by pedrobaeza** [comment]
In Odoo v9, it must use the existing link tracker from Odoo.

**Comment by ivantodorovich** [comment]
~~I'm looking into this.
In order to replace all the original links in the email, I'm thinking of taking advantage of the beautifulsoup library.
Would that be ok, or should I try to do it using regexp?~~

Nevermind. I think I got it working with just regexp.
