### ISSUE TITLE
[15.0] mail_composer_cc_bcc: Mail tracking fails after installing

### ISSUE THREAD

**Issue by linuxivan** [OCA/social#1260]
When u use mail_composer_cc_bcc the module mail_tracking stops working correctly and when you send an email from any place the tracking appears with a block signal.

Before installing:
![image](https://github.com/OCA/social/assets/61226403/2934fc20-3762-4c6b-89fc-dc3c80d405bd)

After installing:
![image](https://github.com/OCA/social/assets/61226403/51f755ff-7e1d-417f-8d53-5e5a8d58e308)

## Module
mail_composer_cc_bcc

**Comment by TTPBruce** [comment]
This is a limitation of the tracking method. When you cc multiple recipients, they all get the same tracking pixel.

Mouseover the first one to see tracking status of the e-mail. Since it is impossible to tell who opened the mail, there is no tracking information for those users.

I think what's needed is a connector module that adds a toggle between CC and tracking, including better display on CC'd e-mails that better indicates when individual tracking is not available.

**Comment by nilshamerlinck** [comment]
fyi `mail_composer_cc_bcc` has been refactored in 17.0 to introduce compatibility with `mail_tracking`, if you have a bit of time your review is welcome ;-) https://github.com/OCA/social/pull/1312
