### ISSUE TITLE
[RFC] bus_presence_override: Chose availability states

### ISSUE THREAD

**Issue by lasley** [OCA/social#186]
Currently Odoo presence (IM availability) states are based purely on a hard coded [AWAY_TIMER](https://github.com/odoo/odoo/blob/fc2e80cb4bcc450762c7ac5cb82a3e2d88062b38/addons/bus/models/bus_presence.py#L11), which is set at 30 minutes of inactivity. `bus_presence_override` module will improve upon this logic by providing the ability for users to select their current availability state - as you would in a standard IM system.

It will accomplish this by adding a two buttons (red, yellow, and green) in the header of the [MessagingMenu](https://github.com/odoo/odoo/blob/fc2e80cb4bcc450762c7ac5cb82a3e2d88062b38/addons/mail/static/src/js/systray.js#L53):

![image](https://user-images.githubusercontent.com/7397578/28749511-c02d0f7c-747e-11e7-9b11-aaf4992b236d.png)

Clicking the red will make you `offline`, the yellow `away`, the green `online`. 

The technical side of this looks fairly simple. We will add an `im_status_custom` to `res.partner` that will be used to overload the [default `_compute_im_status`](https://github.com/odoo/odoo/blob/44276dfdc3b69cd9b834bfa7037671558e6d0078/addons/bus/models/res_partner.py#L14). I think we'll need to break the inheritance chain here in order to be efficient & just rewrite the direct SQL, but I don't think that's too big of a deal in this instance. Alternatively, we could re-iterate the partners after calling super in order to append any manual changes - but I think that's going to do more harm than good.

Does anyone know of anything doing something similar to this? It seems weird to me that we can't control these states manually, so I honestly feel like I'm missing something.

**Comment by woodbrettm** [comment]
@lasley interestingly there have been cases where a "New Message" link shows up right in the red box area you specified. I'm not sure what triggers it to show up because it seems it rarely does.

Perhaps we should put the status below the list of notifications (with a break line, below the 'general' notification). 

Or what about a new icon on the navbar? Next to the chat bubble symbol we could have a new dropdown for the status, with the icon being the color of the persons' availability.

**Comment by lasley** [comment]
New icon will be best
