### ISSUE TITLE
mail_debrand does not work if partner has different language, v12

### ISSUE THREAD

**Issue by gr22** [OCA/social#441]
If the partner has different language than the user sending the mail then `_("Powered by")` would not translate to the partner's lang but the html of the template will so the condition `if powered_by not in html:` will fail

**Comment by astirpe** [comment]
I confirm that this issue occurs, introduced by https://github.com/OCA/social/commit/c706391c2e1f6fc4224a79526d0adc789a43a623#diff-171036ef0b5f4a45ad3a3b313e1fbe0a

Would be nice to restore the old behavior, that was completely removing the "Powered by" part.

**Comment by pedrobaeza** [comment]
@gdgellatly you were the author of it. Can you please check?

**Comment by dndoanh** [comment]
@astirpe It works if you have translation file in that lang

**Comment by astirpe** [comment]
@dndoanh I didn't test it with any .po file, but if I look at [this](https://github.com/OCA/social/tree/12.0/mail_debrand/i18n) I think that you are implicitly confirming the issue for all the languages other than English, right?

**Comment by gdgellatly** [comment]
@gr22 @astirpe I'm a bit confused, it seems there are differing opinions here on what the bug is.

The actual report seems to imply all that is needed is to ensure the translation is performed in the partners language, but I was pretty sure that was already passed in context.

The old way relied on XML navigation, which kind of broke when they changed all the templates for this version, and it also isn't standardised as a single template and has different formats everywhere. 

However we only use Powered By to navigate to the point in the tree, then remove the parent node. Given the name of this module is `debrand` it might be easier to find the `a` tag with `href` instead which should always start `https://www.odoo.com?utm_source=` in every language and remove one level higher

**Comment by pedrobaeza** [comment]
That can work, but the other option is simply: translate in this module the text "Powered by" the same as Odoo does.

**Comment by astirpe** [comment]
I perfectly understand the technical point. But in general we should also put ourselves in the shoes of non-technical users: one installs this module, expecting that the Powered By is removed, but instead it stays there. And the solution with translations is not even mentioned in the readme/configuration.

**Comment by pedrobaeza** [comment]
OK, someone can propose the alternative patch that @gdgellatly mentions

**Comment by gdgellatly** [comment]
@astirpe No one is disagreeing with you, clearly it is a bug that requires fixing. You seem to have the best handle on the right approach so maybe you like to propose a PR.

@pedrobaeza Well the problem with href solution is somewhat the opposite. It catches both the `using` scenario and `Powered by` scenario. Although if I look at the occurrences, there is only one occurrence of `using` so maybe an `if template == mail.message_notification_email: do using stuff; else: do Powered By styff` is enough for handling. Would make the code a lot simpler.

**Comment by BT-panken** [comment]
I confirm the problem:

Current user language: english
Email language (partner): german
Translation used by the module: english

**Comment by chienandalu** [comment]
In v11, we applied this patch: https://github.com/OCA/social/commit/fbca7320b71233081cd8428fa56bba185cf2c9a4

Now in v12 it would be possible to have an even more deterministic way to ensure the translation is the same used in the template as the base is a qweb template and the translated terms are independent.

Anyone wants to do the patch? :)
