### ISSUE TITLE
[11.0][mail_tracking] Dont display spam messages

### ISSUE THREAD

**Issue by Danoolo** [OCA/social#502]
Hello people, I have a question about mail_tracking ... when you send emails and the message reaches spam in the recipient's mailbox I understand that in the info of that message with mail_tracking we can know if it was in "spam" status . But it has happened to us many times that emails reach spam in customers but the status of these messages is "sent." I am working with a ubuntu 16.04 instance with odoo 11.0 and a nginx as a reverse proxy. Some help? Is this a mistake?

**Comment by pedrobaeza** [comment]
It's not an error. mail_tracking can't know if your mail client classifies the mail as spam or the target mail server doesn't inform about that.

That state is thought for certain mail servers like Mailgun that informs back that your mail has been classified as such.

The same happens with the received state. You can only assure in your side that it has been sent. The rest should be informed back, and due to several reasons and spam abuses, this is not usually given.

Closing then as no bug.

**Comment by Danoolo** [comment]
Thanks @pedrobaeza for the help info!!
