### ISSUE TITLE
[mass_mailing_partner] what should happen, when partner is archived?

### ISSUE THREAD

**Issue by rgl1234** [OCA/social#520]
Hello
By testing mass_mailing_partner, it seems that nothing happens, when a subscribed-partner is archived. In my opinion, there should be the following behaviour, when a partner is archived:

1) unsubscribe partner from all mailing-lists
or
2) delete mass-mailing-contact
or
3) other suggestions ?

What do you think about this?
René

**Comment by pedrobaeza** [comment]
Not sure if this automation should be done...

@rafaelbn @Yajo what do you think about this?

**Comment by yajo** [comment]
The archived partner is excluded by default from all searches unless `['archive', '=', False]` or `.with_context(active_test=False)` are explicitly used, so I don't see a reason to do this.

**Comment by pedrobaeza** [comment]
@Yajo that's not what happens with a mass_mailing.contact linked to an archived partner.

**Comment by rgl1234** [comment]
Yes, I f a partner is archived, then mails are still sent to the mailing-list-contact, because the contact is not touched. In my case, I have been asked by the customer to "deactivate" his address in our database, because he has stopped working. I then "unsubscribed" the mass-mailing-contact manually to not  send any mails to him in the future....
Maybe the correct behaviour would be to archive the mass-mailing-contact. But as this functionality is not available by default, I thought to unsubscribe it could be a "work-around"....

**Comment by yajo** [comment]
The user can click in the unsubscribe link in received mass mailings and alter his preferences, right?
I think Odoo has a mail blacklist in recent versions, which would  also serve your purposes if I'm not wrong. Have you considered these options?

**Comment by pedrobaeza** [comment]
@Yajo you are deviating from main purpose. This is not something on the customer side, but on your side. If you deactivate a partner, then all in your system should be consistent. I'm stating to think that yes, linked mass_mailing.contact should be deactivated/removed on that deactivation.

**Comment by yajo** [comment]
I don't think so.

If you have a partner and still have one or several mass mailing contacts with the same address, that's most likely because you want him to be able to manage his subscriptions separately.

The fact you archive a partner means that it's no longer interesting to you; but the fact someone unsubscribes from a mailing list means that it's no longer interesting to him. You have different tools for different purposes. Otherwise just use partners and tags instead of mailing lists.

If you want to do that in your DB, you can also add a automated action that cares for that.

**Comment by pedrobaeza** [comment]
I still think the contrary. The same way we synchronize other fields between partner and mass mailing contact, active one should be. This is the essence of this module, to link/couple both.

@rafaelbn what do you think?

**Comment by rgl1234** [comment]
In my opinion it makes now sence to keep a mass-mailing-contact active, if the linked partner is no longer existing. So in my opinion it should be automated by default.

**Comment by pedrobaeza** [comment]
@rgl1234 your last sentence seems contradictory. Are you with @Yajo or with me in our arguments?

**Comment by rgl1234** [comment]
@pedrobaeza I am same opinion than you are. mass-mailing-contacts should be in sync with partners if there is a link to a partner.....

**Comment by rgl1234** [comment]
> You have different tools for different purposes. Otherwise just use partners and tag

Hello @Yajo can you help me creating an automated action, that takes care of this?

**Comment by rgl1234** [comment]
Hello
I would like to set "opt_out" to "True" for every list the archived-partner is subscribed by automated action. Can someone help me with that?

**Comment by yajo** [comment]
Another option you have is to add a configuration to the module. A check box in `res.config.settings` that enables this behaviour you want. Then, include it in the module as normal code.

**Comment by grindtildeath** [comment]
Jumping in on this discussion since @rgl1234 required us to help in writing an automated action for this. After giving it much thought and although I was thinking adding a configuration in `res.config.settings` was the right move, I now tend to think the opposite.

If the goal of the module is to link mailing contacts to partners, why would we want an active mailing list contact to be linked to an archived partner? From my POV there's no reason to archive a partner if it is linked to an "active" mailing list contact that will receive e-mails from Odoo. Considering this, I feel like the archiving of a partner should either archive the mailing list contact and its subscriptions or be restricted as long as the partner is still linked to a mailing list contact with "active" subscriptions.

However, in terms of usability I don't like the second option that would raise an error asking the user to do more operations in order to be able to archive the partner. I'm therefore in favour of archiving the mailing list contact and its subscriptions, since archiving the partner usually means there is no more relations to him and no reason to keep sending emails.

Since I didn't want to change the behaviour in a released version I opened #520 with two new modules:
 - mass_mailing_contact_active: This module adds an active field on mailing contact and subscription.
 - mass_mailing_partner_contact_active: This module automatically triggers archive/unarchive operations on partner to the mailing list contact and its subscriptions.


Hopefully the second module could be merged in mass_mailing_partner for one of the latest Odoo versions.
