### ISSUE TITLE
[15.0] mail_debrand email frame issue

### ISSUE THREAD

**Issue by Bart-dh** [OCA/social#839]
After installation of the module mail_debrand, the email frame is not as clean as it is supposed to be.

![image](https://user-images.githubusercontent.com/74648219/150821368-38e38475-d826-46ed-84c6-62c7ff30e09b.png)

Without module:
![image](https://user-images.githubusercontent.com/74648219/150821470-781353c1-30ee-464e-bb31-90fb69b54e6c.png)

**Comment by mgielissen** [comment]
Also in 14 with Dutch language

**Comment by jappi00** [comment]
I have the same issue in german

**Comment by jappi00** [comment]
So I have find a quick solution. 
After removing the translation mentioned in the scree
![Bildschirmfoto 2022-04-21 um 13 33 56](https://user-images.githubusercontent.com/13003175/164449654-837e7c72-feaf-43ca-8c3a-b91c492c5a37.png)
nshot everything works.

**Comment by mgielissen** [comment]
The quick fix also works with Dutch translation, remove only the translated value for 'Powered By'

![afbeelding](https://user-images.githubusercontent.com/7700396/164457908-030185a9-8d2b-4cdf-9f11-7d0cae25688c.png)

**Comment by jappi00** [comment]
So I now have looked into the code a little bit further.

Since this line https://github.com/OCA/social/blob/15.0/mail_debrand/models/mail_render_mixin.py#L104 does not work with another language he jumps into this if statement https://github.com/OCA/social/blob/15.0/mail_debrand/models/mail_render_mixin.py#L25

Here the mail body should get splitted around the Customer Written Body:
https://github.com/OCA/social/blob/15.0/mail_debrand/models/mail_render_mixin.py#L29

Somehow this acts very weird and cuts this somewhere between opening and closing html tags. Ffter he generates a tree from the parts (I assume the html gets corrected with closing tags there):
https://github.com/OCA/social/blob/15.0/mail_debrand/models/mail_render_mixin.py#L35

He puts the parts back together:
https://github.com/OCA/social/blob/15.0/mail_debrand/models/mail_render_mixin.py#L58

Since the tags are closed and changed we have different html elements which are wrong closed and seperated. I have no good Idea how we can easy and clean solve this problem.

Maybe somebody else have an idea?

**Comment by klando** [comment]
same issue here. Maybe the expression can be collected from the translations to cover all languages ? (workaround for the underlying bug mentioned by @jappi00 )

**Comment by OKT96** [comment]
same issue here as well on v14. the workaround seems to work - thanks for that

**Comment by alexis-via** [comment]
I confirm the problem with up-to-date code on Odoo v14 : after installation of the mail_debrand module, the mails sent by Odoo have a bad layout.

![mail_debrand_bad_layout](https://user-images.githubusercontent.com/1157917/169110565-9a6c3e26-f7f0-4d33-bc0a-3b457c4747d8.png)

**Comment by rafaelbn** [comment]
Thank you for reporting MT-787 @moduon

**Comment by rafaelbn** [comment]
Closing issue as the solution is in https://github.com/OCA/social/pull/911

**Comment by klando** [comment]
The issue was also against v15. @rafaelbn Can you apply on it also ?

**Comment by Shide** [comment]
@klando yes, we can cherry-pick once is merged :)

**Comment by rafaelbn** [comment]
Merging in v14. Tomorrow we will PR to v15

**Comment by klando** [comment]
@rafaelbn it looks like this addon is breaking digest email, it looks similar to this bug: body content is altered and all < and > are replaced by their html code.
